### ISSUE TITLE
self invocating function doesn't require explicit call.

### ISSUE THREAD

**Issue by asutosh97** [jjsquillante/special-tribble#1]
The function `clockCount` is self invoking, so it doesn't require to be explicity invoked again to run. It runs as soon as you paste the code in the console and press the enter key.
Readme says otherwise.

**Comment by jjsquillante** [comment]
@asutosh97 good catch - I definitely need to clean up some of these repo's as they were created as practice last year and were never really worked on in a detailed manner + I had limited knowledge at that point. I'll go ahead and clean these issues up. Thanks again for looking over the code and finding these bugs!
