### ISSUE TITLE
Callback to setTimeOut

### ISSUE THREAD

**Issue by asutosh97** [jjsquillante/special-tribble#2]
while calling `setTimeOut()`, you are giving it a function which calls `clockCount()` function, as callback, instead of directly passing the `clockCount()` function as callBack function. Any specific reason for that?

**Comment by jjsquillante** [comment]
setTimeout will execute the function either way - I added an unnecessary layer. I think you're questioning is a valid enough reason why, in this scenario, it would be best practice to just pass the function definition. As I mentioned in the previous issue, I wrote this a while back prior to having any true discipline or knowledge from Gordon and W/C. Gordon's helped us all out A LOT :)

**Comment by asutosh97** [comment]
Ya, right.. Gordon and the W/C community he has built out of his hard work.
By the way, are you in gitter or something? I wanted to have a chat.

**Comment by jjsquillante** [comment]
I don't believe my account is active on gitter anymore, but feel free to message me on the W/C slack channel (jjsquillante) or send me an email/gchat  - jjsquillante@gmail.com

**Comment by asutosh97** [comment]
I am not in the W/C slack channel, but I've sent you chat invite over google hangouts. my mail- asutoshsahoo786@gmail.com
